Update README.md
droidconKE/droidconKE2023Android pull request #11
Opened 2023-02-18 10:22 UTC by mertoenjosh

Updated README to droidcon KE 23.

# Scope

_Please make sure to read https://github.com/droidconKE/droidconKE2022Android/docs/CONTRIBUTING.md
and check that you understand and have followed it as best as possible Explain what your feature
does in a short paragraph._ please check the below boxes
- [x] I have followed the coding conventions
- [x] I have added/updated necessary tests
- [x] I have tested the changes added on a physical device
- [x] I have run `./codeAnalysis.sh` to make sure all lint/formatting checks have been done.

## Closes/Fixes Issues
_Declare any issues by typing `fixes #1` or `closes #1` for example so that the automation can kick
in when this is merged_

## Other testing QA Notes
_What have you tested specifically and what possible impacts/areas there are that may need retesting
by others._

Please add a screenshot (if necessary)

2023-02-18 11:18 UTC, chepsi approved these changes

2023-02-18 11:20 UTC, chepsi requested changes

2023-02-18 11:20 UTC, chepsi commented on README.md
>  16-18th 2022.
Can we update this to 
```
Android app for the 4th Android Developer conference- droidcon to be held in Nairobi date to be announced.
```

2023-02-19 08:57 UTC, mertoenjosh commented on README.md
>  16-18th 2022.
Sure

2023-02-19 08:59 UTC, closed without merging